/* tslint:disable */
/* eslint-disable */
/**
 * Notum nodes
 * 🚀🌙
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessDto
 */
export interface AccessDto {
    /**
     * 
     * @type {string}
     * @memberof AccessDto
     */
    access_token: string;
}

/**
 * Check if a given object implements the AccessDto interface.
 */
export function instanceOfAccessDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "access_token" in value;

    return isInstance;
}

export function AccessDtoFromJSON(json: any): AccessDto {
    return AccessDtoFromJSONTyped(json, false);
}

export function AccessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'access_token': json['access_token'],
    };
}

export function AccessDtoToJSON(value?: AccessDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.access_token,
    };
}

