/* tslint:disable */
/* eslint-disable */
/**
 * Notum nodes
 * 🚀🌙
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NodeDto } from './NodeDto';
import {
    NodeDtoFromJSON,
    NodeDtoFromJSONTyped,
    NodeDtoToJSON,
} from './NodeDto';

/**
 * 
 * @export
 * @interface NodesDto
 */
export interface NodesDto {
    /**
     * 
     * @type {Array<NodeDto>}
     * @memberof NodesDto
     */
    nodes: Array<NodeDto>;
}

/**
 * Check if a given object implements the NodesDto interface.
 */
export function instanceOfNodesDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nodes" in value;

    return isInstance;
}

export function NodesDtoFromJSON(json: any): NodesDto {
    return NodesDtoFromJSONTyped(json, false);
}

export function NodesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(NodeDtoFromJSON)),
    };
}

export function NodesDtoToJSON(value?: NodesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nodes': ((value.nodes as Array<any>).map(NodeDtoToJSON)),
    };
}

