/* tslint:disable */
/* eslint-disable */
/**
 * Notum nodes
 * 🚀🌙
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * User id
     * @type {number}
     * @memberof UserDto
     */
    sub: number;
    /**
     * Username
     * @type {string}
     * @memberof UserDto
     */
    username: string;
    /**
     * iat
     * @type {number}
     * @memberof UserDto
     */
    iat?: number;
    /**
     * iat
     * @type {number}
     * @memberof UserDto
     */
    exp?: number;
}

/**
 * Check if a given object implements the UserDto interface.
 */
export function instanceOfUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sub" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function UserDtoFromJSON(json: any): UserDto {
    return UserDtoFromJSONTyped(json, false);
}

export function UserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sub': json['sub'],
        'username': json['username'],
        'iat': !exists(json, 'iat') ? undefined : json['iat'],
        'exp': !exists(json, 'exp') ? undefined : json['exp'],
    };
}

export function UserDtoToJSON(value?: UserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sub': value.sub,
        'username': value.username,
        'iat': value.iat,
        'exp': value.exp,
    };
}

